// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWS8HPHFxK29f7Z0-R_YPW_7T3EjjNpvA',
    appId: '1:912825365518:web:ddfaa088db06bc36ae785f',
    messagingSenderId: '912825365518',
    projectId: 'asynconf-c37eb',
    authDomain: 'asynconf-c37eb.firebaseapp.com',
    storageBucket: 'asynconf-c37eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQOvyVP3hUiUzIYd80KDsg8wE_UJ9H1f8',
    appId: '1:912825365518:android:85b7205395d8f92dae785f',
    messagingSenderId: '912825365518',
    projectId: 'asynconf-c37eb',
    storageBucket: 'asynconf-c37eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXSlcAC5prxX_PRWFQv9hOwDylwFKige8',
    appId: '1:912825365518:ios:d733a475f9d95fedae785f',
    messagingSenderId: '912825365518',
    projectId: 'asynconf-c37eb',
    storageBucket: 'asynconf-c37eb.firebasestorage.app',
    iosBundleId: 'com.example.asynconf2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXSlcAC5prxX_PRWFQv9hOwDylwFKige8',
    appId: '1:912825365518:ios:d733a475f9d95fedae785f',
    messagingSenderId: '912825365518',
    projectId: 'asynconf-c37eb',
    storageBucket: 'asynconf-c37eb.firebasestorage.app',
    iosBundleId: 'com.example.asynconf2025',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWS8HPHFxK29f7Z0-R_YPW_7T3EjjNpvA',
    appId: '1:912825365518:web:51bcfd3cd6d35060ae785f',
    messagingSenderId: '912825365518',
    projectId: 'asynconf-c37eb',
    authDomain: 'asynconf-c37eb.firebaseapp.com',
    storageBucket: 'asynconf-c37eb.firebasestorage.app',
  );
}
